# Generated by Django 2.2 on 2018-11-21 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Supermarkt', '0002_auto_20181121_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KapazitaetRegale', models.IntegerField(default=0)),
                ('Groesse', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Regal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bezeichnung', models.CharField(max_length=256)),
                ('Kapazitaet', models.IntegerField(default=0)),
                ('Standort', models.IntegerField(default=0)),
                ('Groesse', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='produkte',
            name='Anzahl',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produkte',
            name='Standort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supermarkt.Regal'),
        ),
    ]
