# Generated by Django 2.2 on 2018-11-21 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Supermarkt', '0003_auto_20181121_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produkte',
            old_name='Name',
            new_name='Produkt',
        ),
        migrations.AlterField(
            model_name='produkte',
            name='Lieferant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Supermarkt.Lieferant'),
        ),
    ]
