# Generated by Django 2.2 on 2018-11-30 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supermarkt', '0005_auto_20181130_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkte',
            name='Kategorie',
        ),
    ]
