# Generated by Django 2.2 on 2018-11-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supermarkt', '0006_remove_produkte_kategorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkte',
            name='Kategorie',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
