# Generated by Django 2.2 on 2018-12-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Supermarkt', '0007_produkte_kategorie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regal',
            name='Groesse',
        ),
    ]
